//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DUI { get; set; }
        public Nullable<int> Speeding_Tickets { get; set; }
        public string Coverage { get; set; }
        public Nullable<decimal> Quote { get; set; }
    }
}
